#!/bin/sh

missing_tool()
{
    echo 'Could not find Job Router diagnostic tool. Please verify your HTCondor installation.'
    exit 1
}

. /usr/share/condor-ce/condor_ce_env_bootstrap
export GSI_AUTHZ_CONF=/dev/null
CONDOR_BIN_DIR=$(/usr/bin/dirname $(/usr/bin/which condor_version 2> /dev/null ) 2> /dev/null ) 
if [ -z "$CONDOR_BIN_DIR" ]; then
    missing_tool
elif [ -x "$CONDOR_BIN_DIR/condor_job_router_info" ]; then
    exec "$CONDOR_BIN_DIR/condor_job_router_info" "$@"
elif [ -x "$CONDOR_BIN_DIR/condor_job_router_tool" ]; then
    exec "$CONDOR_BIN_DIR/condor_job_router_tool" "$@"
else
    missing_tool
fi 


