#!/bin/sh

# Configuration for LCMAPS
export LLGT_LOG_IDENT=htcondor-ce
export LLGT_VOMS_DISABLE_CREDENTIAL_CHECK=1
export LCMAPS_DB_FILE=/etc/lcmaps.db
export LCMAPS_POLICY_NAME=authorize_only
#level 0: no messages, 1: errors, 2: also warnings, 3: also notices,
#  4: also info, 5: maximum debug
export LCMAPS_DEBUG_LEVEL=2
# this is needed for the authorize_only policy
export LLGT_LIFT_PRIVILEGED_PROTECTION=1

# Pieces of HTCondor obey the same environment variables as Globus
# for port usage.  Mostly Useless due to our use of shared port.
if [ -e /var/lib/osg/globus-firewall ]; then
    . /var/lib/osg/globus-firewall
fi

# Pick up any configuration for condor-ce from /etc/sysconfig.
# The big thing we are looking for is that Condor can sometimes be installed
# into a non-standard location and we need to set it up in the PATH
if [ -f /etc/sysconfig/condor-ce ]; then
    . /etc/sysconfig/condor-ce
fi

CONDOR_CONFIG=/etc/condor-ce/condor_config
export CONDOR_CONFIG

