#!/usr/bin/python

import os
import re
import sys
import time
import socket
import optparse
import tempfile
import traceback

os.environ.setdefault("CONDOR_CONFIG", "/etc/condor-ce/condor_config")

import classad
import htcondor
import htcondorce.tools as ce

G_DEBUG = False

CONDOR_JOB_STATUS = {0: "Unexpanded",
                     1: "Idle",
                     2: "Running",
                     3: "Removed",
                     4: "Completed",
                     5: "Held",
                     6: "Transferring Output",
}

def verify_matching_condor_versions():
    lib_ver = htcondor.version()
    try:
        _, stdout, _ = ce.run_command('condor_version')
    except RuntimeError:
        raise ce.CondorRunException('Could not find version information using condor_version. ' \
                                    'Ensure that condor_version is in your PATH')
    tool_ver = stdout.split('\n')[0]
    if lib_ver != tool_ver:
        raise RuntimeError('Found multiple, mismatched versions of HTCondor libraries. ' \
                           'Please ensure that you only have one version of HTCondor installed.')

def configure_auth():
    try:
        auth_methods = re.split(r",?\s*", htcondor.param['SEC_CLIENT_AUTHENTICATION_METHODS'])
    except KeyError:
        auth_methods = []
    if 'GSI' not in auth_methods:
        auth_methods.append("GSI")

    auth_methods = ",".join(auth_methods)
    os.environ['_condor_SEC_CLIENT_AUTHENTICATION_METHODS'] = auth_methods
    htcondor.param['SEC_CLIENT_AUTHENTICATION_METHODS'] = auth_methods

def run_ping(address, daemon='SCHEDD'):

    if not address.startswith("<"):
        address = "<%s>" % address
    if daemon == "SCHEDD":
        args = ["condor_ce_ping", "-addr", str(address), "-verbose", "-type", daemon, "-debug", "WRITE"]
    else:
        args = ["condor_ce_ping", "-addr", str(address), "-verbose", "-type", daemon, "-debug", "READ"]

    try:
        rc, stdout, _ = ce.run_command(args)
    except RuntimeError, e:
        raise ce.CondorRunException('Failed to ping %s due to the following error:\n%s' % (address, e))

    if G_DEBUG:
        print "*"*5, "condor_ping output", "*"*5
        print stdout,
        print "*"*20

    if rc < 0:
        raise ce.CondorRunException("Failed to ping %s; condor_ping terminated with signal %d." \
                                    % (address, -rc))
    elif rc > 0:
        if re.search('Failed to connect', stdout):
            raise ce.CondorRunException("Failed to ping %s: Please contact the site's system adminstrator to " \
                                        "ensure that the CE you're trying to contact is functional." % address)
        else:
            message = "Failed to ping %s; authorization check exited with code %d." % (address, rc)
            if not G_DEBUG:
                message = message + " Re-run the command with '-d' for more verbose output."
            raise ce.CondorRunException(message)

    unauthorized_user = re.search(r'Remote Mapping:\s*(.*)\nAuthorized:\s*FALSE', stdout, re.MULTILINE)
    if unauthorized_user:
        raise ce.CondorUserException("User %s does not have permissions for %s. Please contact the CE's " \
                                     "system administrator to ensure that your user is mapped properly " \
                                     "in the site's authentication system."
                                     % (unauthorized_user.group(1), address))

def parse_opts():

    usage = "usage: %prog [options] <CE hostname>"
    parser = optparse.OptionParser(usage=usage)
    parser.add_option("-s", "--schedd-name",
                      help="Name of the schedd to use.",
                      dest="schedd_name")
    parser.add_option("-d", "--debug", help="Print debugging info.",
                      dest="debug", default=False, action="store_true")
    parser.add_option("-a", "--attribute", help="Add attribute to job ad.",
                      dest="attribute", default=[], action='append')
    parser.add_option("-n", "--no-clean", help="Do not clean temporary "
                      "files.", dest="clean", default=True, action="store_false")

    opts, args = parser.parse_args()
    global G_DEBUG
    G_DEBUG = opts.debug
    if G_DEBUG and hasattr(htcondor.param, 'setdefault') and hasattr(htcondor, 'enable_debug'):
        htcondor.param.setdefault('TOOL_DEBUG', "D_FULLDEBUG")
        htcondor.enable_debug()

    return opts, args


def check_authz(job_info):
    print "Testing HTCondor-CE collector connectivity."
    try:
        addresses = socket.getaddrinfo(job_info['collector_fqdn'], job_info['collector_port'], 0, socket.SOCK_STREAM)
    except socket.gaierror:
        raise RuntimeError("Failed to retrieve socket information for %s:%s. Verify the specified hostname and " \
                           "network connectivity to the CE." %  (job_info['collector_fqdn'],
                                                                 job_info['collector_port']))
    had_success = False
    for addrinfo in addresses:
        addr = "<%s:%d>" % addrinfo[4][:2]
        try:
            run_ping("<%s:%d>" % addrinfo[4][:2], daemon="COLLECTOR")
            had_success = True
            print "- Successful ping of collector on %s.\n" % addr
        except Exception, e:
            print "- Failed ping of collector on %s.\n" % addr
            raise e

    if not had_success:
        raise ce.CondorRunException("No collector check was successful! Please contact the site's system " \
                                    "adminstrator to ensure that the CE you're trying to contact is functional.")
    coll = htcondor.Collector(job_info['collector_name'])

    try:
        ad = coll.locate(htcondor.DaemonTypes.Schedd, job_info['schedd_name'])
    except (ValueError, IOError):
        raise ce.CondorRunException("Could not find CE's schedd. Please contact the site's system administrator "
                                    "to ensure that CE you're trying to contact is functional.")

    job_info['schedd_ad'] = ad
    addr = ad['MyAddress']
    print "Testing HTCondor-CE schedd connectivity."
    try:
        run_ping(addr)
        print "- Successful ping of schedd on %s.\n" % addr
    except Exception, e:
        print "- Failed ping of schedd on %s.\n" % addr
        raise e


def generate_run_script(job_info):

    job_info['command'] = 'env'
    job_info['arguments'] = ''

    if job_info['command'][0] != '/':
        for pathdir in os.environ.get("PATH", "").split(":"):
            test_path = os.path.join(pathdir, job_info['command'])
            if os.path.exists(test_path):
                job_info['command'] = test_path
                break

    if job_info['arguments']:
        job_info['arguments'] = '"%s"' % ' '.join(["'%s'" % i for i in \
            job_info['arguments']])
    else:
        job_info['arguments'] = ''

    job_info.update(ce.generate_job_files())

def add_job_proxy_info(job_ad):

    subj_rc, subj_stdout, _ = ce.run_command(["voms-proxy-info", "-file", job_ad['x509userproxy'], "-subject"])
    if subj_rc != 0:
        raise ce.CondorUserException("Cannot parse proxy at %s." % job_ad['x509userproxy'])
    subj_stdout = subj_stdout.strip()
    job_ad['x509userproxysubject'] = subj_stdout
    job_ad['x509UserProxyFQAN'] = subj_stdout

    time_rc, time_stdout, _ = ce.run_command(["voms-proxy-info", "-file", job_ad['x509userproxy'], "-timeleft"])
    if time_rc != 0:
        raise ce.CondorUserException("Cannot parse proxy at %s." % job_ad['x509userproxy'])
    time_stdout = int(time_stdout)
    if time_stdout <= 0:
        print "WARNING: available proxy appears to be expired"
    job_ad['x509UserProxyExpiration'] = int(time.time()) + int(time_stdout)

    vo_rc, vo_stdout, _ = ce.run_command(["voms-proxy-info", "-file", job_ad['x509userproxy'], "-vo"])
    if vo_rc == 0:
        job_ad['x509UserProxyVOName'] = vo_stdout.strip()

    fqan_rc, fqan_stdout, _ = ce.run_command(["voms-proxy-info", "-file", job_ad['x509userproxy'], "-fqan"])
    if fqan_rc == 0:
        fqan_lines = [i.strip() for i in fqan_stdout.strip().split('\n')]
        job_ad['x509UserProxyFirstFQAN'] = fqan_lines[0]
        job_ad['x509UserProxyFQAN'] += "," + ",".join(fqan_lines)

    if G_DEBUG:
        print "Job ad, pre-submit:", job_ad

def set_classad_value_type(value):
    if value.lower() == 'true':
        return True
    elif value.lower() == 'false':
        return False
    elif re.match(r'\d+\.\d+$', value):
        return float(value)
    elif re.match(r'\d+$', value):
        return int(value)

    return value

def check_job_submit(job_info):

    job_ad = classad.ClassAd()
    job_ad["Cmd"] = job_info['command']
    job_ad["Args"] = job_info['arguments']
    job_ad['Out'] = job_info['stdout_file']
    job_ad['Err'] = job_info['stderr_file']
    job_ad['Log'] = job_info['log_file']
    job_ad['LeaveJobInQueue'] = classad.ExprTree("( StageOutFinish > 0 ) =!= true")
    for attr in job_info['attribute']:
        key, value = attr.split('=', 1)
        # Accept submit format '+AttributeName'
        job_ad[key.lstrip('+').strip()] = set_classad_value_type(value.strip())
    proxy = os.environ.setdefault("X509_USER_PROXY", "/tmp/x509up_u%d" % os.geteuid())
    if not os.path.exists(proxy):
        raise ce.CondorUserException("Could not find an X509 proxy in %s" % proxy)
    job_ad['x509userproxy'] = proxy
    add_job_proxy_info(job_ad)

    try:
        schedd = htcondor.Schedd(job_info['schedd_ad'])
    except RuntimeError, e:
        raise ce.CondorRunException("Failed to contact schedd at %s due to the following error:\n%s" \
                                    % (job_info['schedd_ad']['Machine'], e))
    print "Submitting job to schedd %s" % job_info['schedd_ad']['MyAddress']
    ad_results = []
    try:
        cluster = schedd.submit(job_ad, 1, True, ad_results)
    except RuntimeError, e:
        raise ce.CondorRunException("- Failed to submit job to %s due to the following error:\n%s" \
                                    % (job_info['schedd_ad']['Machine'], e))

    print "- Successful submission; cluster ID %d" % cluster

    print "Resulting job ad:", ad_results[0]

    print "Spooling cluster %d files to schedd %s" % (cluster, job_info['schedd_ad']['MyAddress'])
    try:
        schedd.spool(ad_results)
    except RuntimeError, e:
        raise ce.CondorRunException("- Failed to spool files to %s due to the following error:\n%s" \
                                 % (job_info['schedd_ad']['Machine'], e))

    print "- Successful spooling"

    attempts = int(htcondor.param.get("CONDOR_CE_TRACE_ATTEMPTS", 600))
    last_status = -1
    for attempt in range(attempts):
        if G_DEBUG:
            print "Querying job status (%d/%d)" % (attempt+1, attempts)
        try:
            ad = schedd.query("ClusterID == %d" % cluster, ["JobStatus", "ClusterID", "ProcID"])
        except RuntimeError, e:
            raise ce.CondorRunException("- Failed to query job status due to the following error:\n%s" %  e)
        if len(ad) != 1:
            raise ce.CondorRunException("Could not find the job in cluster %d" % cluster)
        status = ad[0]['JobStatus']
        if G_DEBUG:
            print "Job status:", CONDOR_JOB_STATUS.get(status, status)
        elif last_status != status:
            if last_status == -1:
                print "Job status:", CONDOR_JOB_STATUS.get(status, status)
            else:
                print "Job transitioned from", CONDOR_JOB_STATUS.get(last_status, last_status), \
                    "to", CONDOR_JOB_STATUS.get(status, status)
            last_status = status
        if status in [3, 4]:
            break
        time.sleep(1)

    if status == 5: # TODO - provide better diagnostics
        raise ce.CondorRunException("Remote job, %d.0, was held" % cluster)
    if status == 4:
        try:
            schedd.retrieve("ClusterID == %d" % cluster)
        except RuntimeError, e:
            raise ce.CondorRunException("Failed to retrieve output from %s due to the following error:\n%s" \
                                        % (job_info['schedd_ad']['Machine'], e))
        try:
            schedd.act(htcondor.JobAction.Remove, "ClusterID == %d" % cluster)
        except RuntimeError, e:
            raise ce.CondorRunException("Failed to cleanup job on %s due to the following error:\n%s" \
                                     % (job_info['schedd_ad']['Machine'], e))
        output = open(job_info['stdout_file'], "r").read()
        if not output:
            raise ce.CondorRunException("Job produced empty stdout")
        if G_DEBUG:
            print "*"*5, "Job output", "*"*5
            print output,
            print "*"*20
        else:
            print "- Job was successful"

def main():
    opts, args = parse_opts()

    if len(args) < 1:
        raise RuntimeError("Usage: condor_ce_trace [options] <hostname>")

    verify_matching_condor_versions()

    job_info = {}
    job_info['attribute'] = opts.attribute
    collector_hostname = args[0].split(":")[0]
    collector_hostname = socket.getfqdn(collector_hostname)
    job_info['collector_fqdn'] = collector_hostname
    port_info = args[0].split(":")[1:]
    if port_info:
        job_info['collector_port'] = int(port_info[0])
    else:
        job_info['collector_port'] = 9619
    collector_hostname = "%s:%d" % (collector_hostname, job_info['collector_port'])
    job_info['collector_name'] = collector_hostname
    if opts.schedd_name:
        job_info['schedd_name'] = opts.schedd_name
    else:
        job_info['schedd_name'] = collector_hostname.split(":")[0]

    configure_auth()
    check_authz(job_info)
    try:
        generate_run_script(job_info)
        check_job_submit(job_info)
    finally:
        if opts.clean:
            ce.cleanup_job_files(job_info)

if __name__ == '__main__':
    try:
        main()
    except (ce.CondorRunException, ce.CondorUserException, RuntimeError), e:
        ce.print_timestamped_msg(e)
        sys.exit(1)
    except Exception, e:
        pid = os.getpid()
        try:
            fd, stack_file = tempfile.mkstemp(dir=".", prefix=".stack_%d_" % pid)
            f = os.fdopen(fd, 'w')
            f.write('%s\n' % time.strftime('%Y-%m-%d %H:%M:%S'))
            traceback.print_exc(file=f)
            f.close()
            ce.print_formatted_msg('Uncaught exception, please send %s to goc@opensciencegrid.org with a description ' \
                                   'of the issue.' % stack_file)
        except OSError, e:
            ce.print_formatted_msg("Unable to write stackfile due to the following error:\n%s" % e)
        sys.exit(1)
