#!/usr/bin/python
import os
import sys
import optparser

# HTCondor-CE simple run script.

def parse_opts():
    parser = optparser.OptionParser()
    parser.add_option("-x", "--extra-attributes-file",
        help="A file containing additional HTCondor ClassAd attributes to append to the submit ClassAd.",
        dest="extra_attrs_file")
    parser.disable_interspersed_args()

    opts, args = parser.parse_args()

    return opts, args

def generate_run_script():
    raise NotImplementedError()

def wait_for_job():
    raise NotImplementedError()


def main():
    opts, args = parse_opts()

    if len(args) < 2:
        print "Usage: condor_ce_run <hostname> <command> [arg1] [arg2] [...]"

    

if __name__ == '__main__':
    main()

